services:

  video-processing:
    build:
      context: video/
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}



volumes:
  postgres_data:
  minio_data: